# Dark theme style - Colodore palette (default)
h1 = "white"
h2 = "yellow"
h3 = "light_green"
h4 = "cyan"
h5 = "light_grey"
h6 = "grey"
code_bg = "black"
code_label = "cyan"
bullet = "cyan"
table_header_bg = "blue"
table_border = "grey"
blockquote_border = "grey"
think_border = "grey"
hr = "dark_grey"
link_url = "grey"
image_marker = "cyan"
footnote = "cyan"
